# A generic, single-database configuration.

[alembic]
# path to migration scripts
script_location = migrations

# template used to generate migration files
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug)s

# sys.path path, pathsep delimited, prepend to sys.path.
# Defaults to the current directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# timezone = UTC

# max length of characters to use for "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow quantity flag to be passed
# to the 'revision' command
# flag_type = false

# version locations override; list of directories where
# version files are written. Defaults to migrations/versions.
# version_locations = %(here)s/bar

# version_path_separator = :

# set to 'true' to search for schemas in the database.
# Defaults to 'false' if not specified.
# search_schemas = false

# set to 'true' to write migration scripts in a separate transaction.
# Defaults to 'false' if not specified.
# transaction_per_migration = false


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# immediately after a migration script is generated.

# format using "ruff" if available
# hooks = ruff
# ruff.type = console_scripts
# ruff.entrypoint = ruff
# ruff.options = format REVISION_SCRIPT_FILE

[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARNING
handlers = console
qualname =

[logger_sqlalchemy]
level = WARNING
handlers =
qualname = sqlalchemy.engine
# "level = INFO" will show SQL statements.
# "level = DEBUG" will show SQL statements and results.
# "level = WARNING" will show neither.

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stdout,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
