name: api_client
description: Reusable HTTP client
version: 0.0.1
resolution: workspace

environment:
  sdk: ^3.12.2

dependencies:
  dio: ^5.9.0
  shared_models:
    path: ../shared_models

dev_dependencies:
  lints: ^6.0.0
