services:
  postgres:
    image: postgres:17
    container_name: expenseflow-postgres
    restart: unless-stopped
    ports:
      - '5432:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: expenseflow
    volumes:
      - postgres_data:/var/lib/postgresql/data

  garage:
    image: dxflrs/garage:v2.0.0
    container_name: expenseflow-garage
    restart: unless-stopped
    ports:
      - "3900:3900" # S3 API
      - "3903:3903" # Admin API
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  garage-init:
    image: dxflrs/garage:v2.0.0
    container_name: expenseflow-garage-init
    depends_on:
      - garage
    entrypoint: /bin/sh /init-garage.sh
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
      - ./init-garage.sh:/init-garage.sh:ro
      - ./shared:/shared
      - garage_meta:/var/lib/garage/meta
      - garage_data:/var/lib/garage/data

  garage-ui:
    image: khairul169/garage-webui:latest
    container_name: expenseflow-garage-ui
    restart: unless-stopped
    ports:
      - "3909:3909"
    volumes:
      - ./garage.toml:/etc/garage.toml:ro
    environment:
      API_BASE_URL: "http://garage:3903"
      S3_ENDPOINT_URL: "http://garage:3900"

volumes:
  postgres_data:
  garage_meta:
  garage_data:
