name: expenseflow_workspace

environment:
  sdk: ">=3.12.2 <4.0.0"

workspace:
  - apps
  - backend/api
  - packages/api_client
  - packages/shared_models
  - packages/shared_utils

dev_dependencies:
  melos: ^8.2.2

dependency_overrides:
  cli_util: ^0.5.0